import { Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export const COLORS = {
    TEXT : {
        primary:"#000000",
        secondary : "#767475",
        header: "#000000",
        black:"#000000",
        white:"#FFFFFF"
    },
    VIEW:{
        primary: "rgba(255, 64, 64, 1)",  
        secondary: "#fd5f00",
        secondary60:"#767475",
        secondary20:"#d6d5d3",
        secondary80:"#666666",
        shadow: "lightgrey", 
        busy:'#CFD0D7',
        white: '#FFFFFF',
        darkGray: "#757D85",
        black: "#000000",
        mindfullyOrangeDark: "#d49037",
        transparent: 'transparent',
    },
    ONBOARDING: {
        dotActive: "rgba(255, 64, 64, 1)",
        dotPassive: "#3a1a1a",

    },
    primary: "#ffd600",  
    secondary: "#ffea77",
    fontPrimary:"#000000",
    drawerPrimary: "#FFFFFF",
    buttonprimary: "#3a1a1a", //gray
    tabprimary: "#fd5f00",
    tabsecondprimary: "#505f73",
    titleprimary:"#394855",
    transparentPrimary: 'rgba(227, 120, 75, 0.4)',
    transparentPrimary9: 'rgba(255, 238, 233, 0.9)',
    orange: "#14EAE6",
    mindfullyOrange: "#f4be78",
    mindfullyOrangeDark: "#d49037",
    lightOrange: "#1FA133",
    allstarsyellow: "#f0de00",
    lightOrange2: "#1DDED4",
    lightOrange3: '#1FD9AD',
    green: "#27AE60",
    red: "#D06412", 
    blue: '#0064C0',
    darkBlue: "#111A2C",
    darkGray: "#2a475b",
    darkGray2: "#757D85",
    gray: "#898B9A",
    gray2: "#BBBDC1",
    gray3: '#CFD0D7',
    lightGray1: "#FAFAFA",
    lightYellow: "#fec52d",
    lightGray2: "#F5F5F8",
    white2: "#FBFBFB",
    white: '#FFFFFF',
    black: "#000000",
    mainbackgrpund: "#f9f9fb",
    transparent: 'transparent',
    transparentWhite1: "rgba(255, 255, 255, 0.1)",
    lightGrayBackground: "rgba(250, 250, 250, 1)",

    transparentBlack1: "rgba(0, 0, 0, 0.1)",
    transparentBlack7: "rgba(0, 0, 0, 0.7)",
    videoThumbnailTop: 10,
    videoThumbnailLeft: 20,
    videoThumbnailHeight: 90,
    videoThumbnailWidth: 120,

};
export const SIZES = {
    VIEW: {
        header:80,
        bottom:10,
        top:10,
        cardIcon:16,
        playlistHeight: 750,
        radius: 12,
        buttonHeight:60,
        buttonWidth: 200,
    },
    WORKOUT: {
        card:70,
        cardInsideImage:60,
        cardPlaylistImage:80,
        cardIcon:16,
        bannerHeight:250,
    },
    ONBOARDING: {
      dotHeight: 10,
      dotRadius: 6,
      dotMargin: 5, 
      footerHeight:160,
      padding:24,    
      height: 160, 
    },
    PLAYER: {
        playingIconTop:0,
        playingIconLeft:0,
        playingIconSize:40,
        padding:10,
        radius:12,
    },
    KPI:{
        kpiCardHeight: 120,
        kpiPadding:5,
    },
    // global sizes
    base: 8,
    font: 14,
    radius: 12,
    circle: 30,
    padding: 24,
    header: 100,
    icon: 50,
    userboardingbuttonheight: 94,
    userboardingbuttonwidth: 104,

    userboardingbuttonborder: 1,
    workOutCardHeight: 160,
    cardHeight: 120,
    workOutCardRadius: 16,
    exerciseCardRadius: 16,
    workOutCardHeight: 120,
    // font sizes
    largeTitle: 40,
    h1: 30,
    h2: 22,
    h3: 16,
    h4: 14,
    h5: 12,
    h6: 40,
    h7: 32,
    body1: 32,
    body2: 22,
    body3: 16,
    body4: 14,
    body5: 12,
    body5: 10,
    videoPlayHeight: 36,
    videoThumbnailTop: 0,
    videoThumbnailLeft: 20,
    videoThumbnailHeight: 60,
    videoThumbnailWidth: 60,
    exerciseCardHeight: 90,
    loadingIndicatorHeight: 200,
    newsBannerHeight: 200,
    homepageCardHeight: 100,
    programCardWidth:160,
    // app dimensions
    width,
    height
};
export const FONTS = {
    largeTitle: { fontFamily: "Lato-Regular", fontSize: SIZES.largeTitle },
    h1: { fontFamily: "Lato-Regular", fontSize: SIZES.h1, lineHeight: 36 },
    h1: { fontFamily: "Lato-Regular", fontSize: SIZES.h1, lineHeight: 36 },
    h2: { fontFamily: "Lato-Regular", fontSize: SIZES.h2, lineHeight: 30 },
    h3: { fontFamily: "Lato-Regular", fontSize: SIZES.h3, lineHeight: 22 },
    h4: { fontFamily: "Lato-Regular", fontSize: SIZES.h4, lineHeight: 22 },
    h6: { fontFamily: "Lato-Regular", fontSize: SIZES.h6, lineHeight: 46 },
    h7: { fontFamily: "Lato-Regular", fontSize: SIZES.h7, lineHeight: 22 },
    body1: { fontFamily: "Lato-Regular", fontSize: SIZES.body1, lineHeight: 36 },
    body2: { fontFamily: "Lato-Regular", fontSize: SIZES.body2, lineHeight: 30 },
    body3: { fontFamily: "Lato-Regular", fontSize: SIZES.body3, lineHeight: 22 },
    body4: { fontFamily: "Lato-Regular", fontSize: SIZES.body4, lineHeight: 20 },
    body5: { fontFamily: "Lato-Regular", fontSize: SIZES.body5, lineHeight: 18 },
    body6: { fontFamily: "Lato-Regular", fontSize: SIZES.body6, lineHeight: 20 },
    body1Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body1, lineHeight: 36 },
    body2Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body2, lineHeight: 30 },
    body3Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body3, lineHeight: 22 },
    body4Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body4, lineHeight: 20 },
    body5Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body5, lineHeight: 18 },
    body6Bold: { fontFamily: "Lato-Bold", fontSize: SIZES.body6, lineHeight: 20 },
    body7Bold: { fontSize: SIZES.body3, fontWeight: "500", },
};

const appTheme = { COLORS, SIZES, FONTS };

export default appTheme;