/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://kb2uwnq6tj.execute-api.eu-central-1.amazonaws.com/rescued",
            "region": "eu-central-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ionwvh7ifbhatfax4rcaz27uzu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:f0ede6e4-328d-46df-97e7-cb792dff0f65",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_nUGZ9jWgt",
    "aws_user_pools_web_client_id": "2f9s223gdsv9qnq8a8qd2jpn52",
    "oauth": {
        "domain": "ptapp.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "phone",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "AllStarsApp://",
        "redirectSignOut": "AllStarsApp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "allstar-backend-storage-701b3da8223335-rescued",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
